server:
  port: 8888
spring:
  jersey:
    application-path: zj
  datasource:
    url: jdbc:mysql://47.108.185.172:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: smartCtyp@ssw0rd
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  # 指定 mapper.xml 的位置
  mapper-locations: classpath:mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.zj.entity
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true
flowable:
  # 关闭定时任务
  async-executor-activate: false