spring:
  jersey:
    application-path: zj
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&serverTimezone=UTC
    username: root
    password: 6258077
    driver-class-name: com.mysql.cj.jdbc.Driver